# Generated by Django 3.2.16 on 2022-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=10)),
                ('narx', models.IntegerField()),
                ('malumot', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cobalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=10)),
                ('narx', models.IntegerField()),
                ('malumot', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Damas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=20)),
                ('narx', models.IntegerField()),
                ('malumot', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Malibu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=20)),
                ('narx', models.IntegerField()),
                ('malumot', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ravon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=20)),
                ('narx', models.IntegerField()),
                ('malumot', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=20)),
                ('narx', models.IntegerField()),
                ('malumot', models.TextField()),
            ],
        ),
    ]
