# Generated by Django 3.2.16 on 2022-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ichshilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('vazifasi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MalakaliIshchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('vazifasi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mutaxasislar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('tajriba', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Professionallar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('tajribasi', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rahbarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=22)),
                ('yosh', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='TexnikXodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('vazifasi', models.TextField()),
            ],
        ),
    ]
